import React from 'react'
import Typography from '@material-ui/core/Typography';
import classNames from 'classnames'
import Grid from '@material-ui/core/Grid';

import CarbosChains from '../../images/carbos_chains_image.svg'
import CarbosCycle from '../../images/carbos_cycle_image.svg'
import CarbosProperty from '../../images/carbos_property_image.svg'

import { styles } from './styles'
export const About = props => {
  const classes = styles();
  return(
    <div className={classes.root}>
      <div className={classes.container}>
        <Typography className={classes.title} variant="h4">
          How does carbos work?
        </Typography>

        <Typography className={classes.textOnlyRow} variant="body1">
          We believe that all carbon negative actions– regardless of scale– are part of a global solution to climate change, which is why we're working to connect environmentally progressive businesses with local carbon neturality solutions.  
        </Typography>


        {/* <Typography className={classes.paragraph} variant="body1">
          Our platform allows landowners to evaluate and sell carbon offsets generated by land conservation on their properties.
        </Typography> */}

        <Grid container>
           <Grid item xs={12} sm={9} className={classes.imageSwapOrder}>
            <Typography className={classNames([classes.textWithImage])} variant="body1">
              Our platform allows landowners to evaluate and sell carbon offsets generated by land conservation on their properties.
            </Typography>
          </Grid>
          <Grid item xs={12} sm={3} className={classNames([classes.imageWrapper, classes.mobileFirst])}>
            <img alt="carbos" src={CarbosProperty}/>
          </Grid>
        </Grid>

        <Grid container>
          <Grid item xs={12} sm={4} className={classes.imageWrapper}>
            <img alt="carbos" src={CarbosChains}/>
          </Grid>
          <Grid item xs={12} sm={8}>
          <Typography className={classNames([ classes.textWithImage])} variant="body1">
            Carbos leverages the Ethereum blockchain to add transparency and security to the offset process by directing businesses to purchase carbon directly from landowners rather than via a thrid-party registry.
          </Typography>
          </Grid>
        </Grid>

        <Grid container>
           <Grid item xs={12} sm={7}>
            <Typography className={classNames([classes.textWithImage])} variant="body1">
              We maximize the benefits of carbon neutrality for both businesses and landowners through community reinvestment and local ecosystem service preservation.           
            </Typography>
          </Grid>
          <Grid item xs={12} sm={5} className={classes.imageWrapper}>
            <img alt="carbos" src={CarbosCycle}/>
          </Grid>
        </Grid>

        {/* <Typography className={classes.paragraph}  variant="body1">
              We maximize the benefits of carbon neutrality for both businesses and landowners through community reinvestment and local ecosystem service preservation. 
        </Typography> */}

      </div>
    </div>
  )
}